### ISSUE TITLE
Próximo dojo

### ISSUE THREAD

**Issue by claytonaalves** [ellotecnologia/dojo#1]
E aí jovens, levanto aqui alguns questionamentos sobre o próximo dojo.

Data ?

* [x] Sexta-feira a partir das 17:30
* [ ] Sábado a partir das 08:00

Qual linguagem iremos utilizar?

* [ ]  Java
* [ ]  Javascript
* [x]  Python
* [ ]  PHP
* [ ]  Pascal
* [ ] Go

Qual o problema iremos resolver ?

@MauricioLeeal @mendesvalentim @zahaila

**Comment by zaioll** [comment]
Nós podíamos usar uma linguagem fortemente tipada também, né?
Pois tem alguns problemas de algorítmos que se forem feitos tipo em PHP ou Js ficaria muito fácil.

**Comment by claytonaalves** [comment]
@zahaila tem alguma sugestão? Java e Pascal possuem tipagem estática forte.

**Comment by zaioll** [comment]
Pascal ou C#.

**Comment by claytonaalves** [comment]
Eu sugiro GO

**Comment by zaioll** [comment]
kkkkkkkkkkkk

**Comment by claytonaalves** [comment]
Sério pow. É mais fácil subir o ambiente de go do que de C#/Java/Pascal... E go já vem com facilidades de criar os unittests nativo.

Pra Pascal eu teria que instalar o DUnit.

Pra Java teria que instalar o JUnit.

Pra C# teria que instalaro NUnit.

Mas é só minha opinião.

**Comment by mendesvalentim** [comment]
Pode ser GO, eu nunca nem vi essa linguagem

**Comment by zaioll** [comment]
> Suponha  um  terminal  PDV  (ponto-de-venda)  que,  para  facilitar  a  vida  do  operador,  diga quantas moedas tem que ser dadas de troco ao cliente.
> 
> As moedas existentes (em número suficiente) são de $0.01, $0.05, $0.25 e $1.00.
> 
> Faça um algoritmo que dê a combinação mínima de moedas a ser dada de troco. O valor 
> total da compra bem como o valor pago pelo cliente são lidos da entrada. 
>
> Imprima apenas os valores das quantidades de moedas efetivamente utilizadas (como “x moedas de Y”), ou a mensagem “sem troco”.


Esse poderia ser feito pelo pessoal que está aprendendo a programar. O que acham?

**Comment by zaioll** [comment]
`Uma palavra é dita palíndrome se ela puder ser lida da mesma forma nos dois sentidos de escrita. Faça um algorítmo que leia uma palavra do usuário e diga se ela é ou não palíndrome.`

Outro pra iniciantes.

**Comment by zaioll** [comment]
E um desafiante....

![selecao_028](https://user-images.githubusercontent.com/31548426/53983605-f39b9f80-40ed-11e9-9603-626e2202f87f.png)

**Comment by claytonaalves** [comment]
Ganha o que tiver mais likes.

**Comment by MauricioLeeal** [comment]
Por mim pode ser GO, nunca ouvi e nem vi nada sobre

**Comment by claytonaalves** [comment]
Diz o @zahaila que resolveu aqui nesse commit 658d94a220a0 .. depois vou testar pra ver.

**Comment by claytonaalves** [comment]
Fiz os testes e realmente está passando.

<img src="https://github.com/ellotecnologia/dojo/blob/master/php/phptest_run.png?raw=true" />

Parabéns @zahaila :clap: :clap: :clap: 

Quem quiser reproduzir, eu coloquei as instruções [aqui](https://github.com/ellotecnologia/dojo/tree/master/php).

**Comment by zaioll** [comment]
Vamos ter dojo hoje? @claytonaalves já está com fígado zero bala pra tomar, ops, codar?

**Comment by claytonaalves** [comment]
:smile: abre uma outra issue... bota pilha na galera aí, eles são muito parados e ficam esperando. A iniciativa precisa vir de todos. :hugs:
